### ISSUE TITLE
Error adding entities for domain climate with platform bgh_smart

### ISSUE THREAD

**Issue by dbrachom** [mool/home-assistant-bgh-smart#13]
Hola, intente instalar la integracionistas según instrucciones via HACS pero estoy recibiendo el siguiente error:

Hi, I tried to install this integration acceding to the instruction provided via HACS but I'm getting the following error:

"2023-01-06 16:58:29.510 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform bgh_smart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 245, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'unknown' is not a valid HVACMode
2023-01-06 16:58:29.512 ERROR (MainThread) [homeassistant.components.climate] Error while setting up bgh_smart platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 297, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 245, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'unknown' is not a valid HVACMode"

Alguien podría ayudarme a validar que esta pasando?, seguí las instrucciones según lo descrito pero no he logrado levantan el componente. muchas gracias!!!

Does anyone can help me t figured out what's happening , thank !!!

**Comment by Juanma04** [comment]
Hola @dbrachom !

Me pasó lo mismo cuando lo instalé. Si te fijas el error, te indica que 'unknown' no es válido como modo HVACMode. El problema es simplemente que al menos uno de los A/A que está en la cuenta está offline, entonces no informa el estado, y por defecto lo toma como STATE_UNKNOWN que no es válido. Lo que hice para saltar ese error fue modificar el archivo climate.py desde el File Editor (/config/custom_components/bgh_smart/climate.py) poniendo como estado inicial STATE_OFF en lugar de STATE_UNKNOWN, de la siguiente forma:

![image](https://user-images.githubusercontent.com/15800038/211094461-94cfa3d6-6a83-4cce-817c-92d20b3b7d50.png)

De esa forma, te va a iniciar bien el módulo, aunque claramente hasta que no resuelvas el problema del A/A que está offline no vas a poder operar con él. En mi caso yo tengo 2 y uno estaba offline, por eso el error.

Espero que te sea de ayuda, cualquier duda me comentas, saludos!

**Comment by dbrachom** [comment]
Hola @Juanma04,

Muchas gracias por tus comentarios, realmente me sirvieron mucho de guía y de gran ayuda, problema resuelto el modulo ya esta caminando y si efectivamente me toco mirar uno de los A/A para así colocarlo nuevamente en Linea.

Tema resuelto una ves mas, Gracias!!!
