### ISSUE TITLE
Cannot set up fan mode to medium 

### ISSUE THREAD

**Issue by damian-barsotti** [mool/home-assistant-bgh-smart#5]
Hi,
First of all, I want to thank your addon. It was very useful to me.
I would like to report a small issue (and a possible solution) when trying to set up the fan mode to 'medium' with the Home Assistant web UI. I couldn't configure it and saw the following log error:
 
```
2021-03-14 12:48:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2938816712] 'medium'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 422, in async_set_fan_mode
await self.hass.async_add_executor_job(self.set_fan_mode, fan_mode)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/bgh_smart/climate.py", line 207, in set_fan_mode
self.set_mode()
File "/config/custom_components/bgh_smart/climate.py", line 180, in set_mode
self._client.set_mode(
File "/usr/local/lib/python3.8/site-packages/pybgh/__init__.py", line 142, in set_mode
'fanMode': FAN_MODE[fan],
KeyError: 'medium'

```
I have been able to fix this problem replacing this code line:
home-assistant-bgh-smart/custom_components/bgh_smart/climate.py
@@ -31,7 +31,7 @@
 
 FAN_AUTO = 'auto'
 FAN_LOW = 'low'
-FAN_MEDIUM = 'mid'
+FAN_MEDIUM = 'medium'
 FAN_HIGH = 'high'
 
I suppose the problem is because the pybgh library uses 'mid' instead of 'medium' key. 

I hope this helps,
Damian.

**Comment by mool** [comment]
Thanks for the feedback! I've just fixed the issue 👍
